{
 "title": "Cisco Switch",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "System Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"snmp\"} / 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "iosVersion{job=\"snmp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='snmp'}[5m])*8",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job='snmp'}[5m])*8",
     "legendFormat": "{{instance}} {{interface}}"
    }
   ]
  }
 ]
}